# Assignment 10: Data and Code Management
## Libby Kokes
### 6/8/26

## Question 1: Read the crunchbase_odm_orgs.csv CSV file into a Pandas data frame and drop records where company names are None values:
- Print the count of records (rows) in the resulting data frame
- Print the first 5 records of the data frame

In [1]:
import pandas as pd

df = pd.DataFrame(pd.read_csv("crunchbase_odm_orgs.csv"))
print("The number of null records is", df["name"].isna().sum())
print("Meanwhile the number of records whose company name is actually 'None' is", (df["name"] == "None").sum())
nonnull = df.dropna(subset=["name"])
print("The CSV contains", len(nonnull), "rows") # Count records
nonnull.head()

The number of null records is 0
Meanwhile the number of records whose company name is actually 'None' is 0
The CSV contains 9999 rows

,uuid,name,type,primary_role,cb_url,domain,homepage_url,logo_url,facebook_url,twitter_url,linkedin_url,combined_stock_symbols,city,region,country_code,short_description
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint,organization,company,https://www.crunchbase.com/organization/wetpai...,wetpaint.com,http://www.wetpaint.com/,https://res.cloudinary.com/crunchbase-producti...,https://www.facebook.com/Wetpaint,https://twitter.com/wetpainttv,https://www.linkedin.com/company/wetpaint,NaN,New York,New York,USA,Wetpaint offers an online social publishing pl...
1,bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7,Zoho,organization,company,https://www.crunchbase.com/organization/zoho?u...,zoho.com,https://www.zoho.com/,https://res.cloudinary.com/crunchbase-producti...,http://www.facebook.com/zoho,http://twitter.com/zoho,http://www.linkedin.com/company/zoho-corporati...,NaN,Pleasanton,California,USA,"Zoho offers a suite of business, collaboration..."
2,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg,organization,company,https://www.crunchbase.com/organization/digg?u...,digg.com,http://www.digg.com,https://res.cloudinary.com/crunchbase-producti...,http://www.facebook.com/digg,http://twitter.com/digg,http://www.linkedin.com/company/digg,NaN,New York,New York,USA,Digg Inc. operates a website that enables its ...
3,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,organization,company,https://www.crunchbase.com/organization/facebo...,facebook.com,http://www.facebook.com,https://res.cloudinary.com/crunchbase-producti...,https://www.facebook.com/facebook/,https://twitter.com/facebook,http://www.linkedin.com/company/facebook,nasdaq:FB,Menlo Park,California,USA,Facebook is an online social networking servic...
4,b08efc27-da40-505a-6f9d-c9e14247bf36,Accel,organization,investor,https://www.crunchbase.com/organization/accel?...,accel.com,http://www.accel.com,https://res.cloudinary.com/crunchbase-producti...,http://www.facebook.com/accel,http://twitter.com/accel,https://www.linkedin.com/company/accel-vc/,NaN,Palo Alto,California,USA,Accel is an early and growth-stage venture cap...

## Question 2: Create a data frame that contains only the records of USA-based companies whose name starts with "Ac":
- Print the count of records (rows) in the resulting data frame
- Print the first 5 records of the data frame

In [2]:
usaac = nonnull[(nonnull["country_code"] == "USA") & (nonnull["name"].str.contains(r"^Ac", regex=True))] # carrot means 'starts with'
print("The resulting rows of the subset dataframe are", len(usaac))
usaac.head()

The resulting rows of the subset dataframe are 31

,uuid,name,type,primary_role,cb_url,domain,homepage_url,logo_url,facebook_url,twitter_url,linkedin_url,combined_stock_symbols,city,region,country_code,short_description
4,b08efc27-da40-505a-6f9d-c9e14247bf36,Accel,organization,investor,https://www.crunchbase.com/organization/accel?...,accel.com,http://www.accel.com,https://res.cloudinary.com/crunchbase-producti...,http://www.facebook.com/accel,http://twitter.com/accel,https://www.linkedin.com/company/accel-vc/,NaN,Palo Alto,California,USA,Accel is an early and growth-stage venture cap...
186,ed54b2d5-f2f1-d4e9-9bbe-40961ff08d44,Action Engine,organization,company,https://www.crunchbase.com/organization/action...,actionengine.com,http://www.actionengine.com,https://res.cloudinary.com/crunchbase-producti...,NaN,NaN,https://www.linkedin.com/company/actionengine,NaN,Foster City,California,USA,Action Engine is an agile software development...
278,64a76f34-4e68-2eb6-d943-9465f39155cd,ActiveWorlds,organization,company,https://www.crunchbase.com/organization/active...,activeworlds.com,http://www.activeworlds.com,https://res.cloudinary.com/crunchbase-producti...,http://www.facebook.com/activeworlds3d,http://twitter.com/activeworlds3d,NaN,NaN,Las Vegas,Nevada,USA,Active Worlds is a 3D virtual reality platform...
1244,ef598b5b-d588-c21f-9b93-be78443f4e22,Acquia,organization,company,https://www.crunchbase.com/organization/acquia...,acquia.com,http://acquia.com,https://res.cloudinary.com/crunchbase-producti...,http://www.facebook.com/acquia,http://twitter.com/Acquia,http://www.linkedin.com/company/167056,NaN,Boston,Massachusetts,USA,Acquia specializes in providing cloud-based di...
1879,135f427d-7f25-9492-1ffe-801b35b6b988,Academic Capital Exchange,organization,company,https://www.crunchbase.com/organization/academ...,academicapital.com,http://www.academicapital.com,https://res.cloudinary.com/crunchbase-producti...,NaN,NaN,NaN,NaN,Chicago,Illinois,USA,"Academic Capital Exchange (ACE), a peer-to-pee..."

## Question 3: Convert the data frame from the previous step into a list of JSON objects:
- Print the count of JSON objects
- Print the first 5 JSON objects
- Write all JSON objects into a text (JSON string) file
- Print the number of records in the resulting file

In [3]:
import json

usaac_json = json.loads(usaac.to_json(orient="records")) # Given that orientation, each list element is 1 company
print("The count of JSON objects is", len(usaac_json))
print("\nAnd the original dataframe record count was", len(usaac)) # Get confirmation

print("\nHere are the first 5 records:\n", json.dumps(usaac_json[:5], indent= 2)) 
# Slicing first 5 records and making them readable

with open("US_Based_Ac_Companies.json", "w") as f:
    json.dump(usaac_json, f, indent=2)
    
print("\nThe record count of this newly-saved file hasn't changed, it's still", len(usaac_json), "rows long")

The count of JSON objects is 31

And the original dataframe record count was 31

Here are the first 5 records:
 [
  {
    "uuid": "b08efc27-da40-505a-6f9d-c9e14247bf36",
    "name": "Accel",
    "type": "organization",
    "primary_role": "investor",
    "cb_url": "https://www.crunchbase.com/organization/accel?utm_source=crunchbase&utm_medium=export&utm_campaign=odm_csv",
    "domain": "accel.com",
    "homepage_url": "http://www.accel.com",
    "logo_url": "https://res.cloudinary.com/crunchbase-production/image/upload/kxcwecxf439wsgluv7jv",
    "facebook_url": "http://www.facebook.com/accel",
    "twitter_url": "http://twitter.com/accel",
    "linkedin_url": "https://www.linkedin.com/company/accel-vc/",
    "combined_stock_symbols": null,
    "city": "Palo Alto",
    "region": "California",
    "country_code": "USA",
    "short_description": "Accel is an early and growth-stage venture capital firm that powers a global community of entrepreneurs."
  },
  {
    "uuid": "ed54b2d5-f2f1-d4e9-9bbe-40961ff08d44",
    "name": "Action Engine",
    "type": "organization",
    "primary_role": "company",
    "cb_url": "https://www.crunchbase.com/organization/actionengine?utm_source=crunchbase&utm_medium=export&utm_campaign=odm_csv",
    "domain": "actionengine.com",
    "homepage_url": "http://www.actionengine.com",
    "logo_url": "https://res.cloudinary.com/crunchbase-production/image/upload/ubyv0j9it0vpkefruxr4",
    "facebook_url": null,
    "twitter_url": null,
    "linkedin_url": "https://www.linkedin.com/company/actionengine",
    "combined_stock_symbols": null,
    "city": "Foster City",
    "region": "California",
    "country_code": "USA",
    "short_description": "Action Engine is an agile software development, design and data services agency"
  },
  {
    "uuid": "64a76f34-4e68-2eb6-d943-9465f39155cd",
    "name": "ActiveWorlds",
    "type": "organization",
    "primary_role": "company",
    "cb_url": "https://www.crunchbase.com/organization/activeworlds?utm_source=crunchbase&utm_medium=export&utm_campaign=odm_csv",
    "domain": "activeworlds.com",
    "homepage_url": "http://www.activeworlds.com",
    "logo_url": "https://res.cloudinary.com/crunchbase-production/image/upload/v1397180850/e53e7f472d5954396a2572c7d6548365.png",
    "facebook_url": "http://www.facebook.com/activeworlds3d",
    "twitter_url": "http://twitter.com/activeworlds3d",
    "linkedin_url": null,
    "combined_stock_symbols": null,
    "city": "Las Vegas",
    "region": "Nevada",
    "country_code": "USA",
    "short_description": "Active Worlds is a 3D virtual reality platform enabling users to build, enter and move about in worlds and interact with others."
  },
  {
    "uuid": "ef598b5b-d588-c21f-9b93-be78443f4e22",
    "name": "Acquia",
    "type": "organization",
    "primary_role": "company",
    "cb_url": "https://www.crunchbase.com/organization/acquia?utm_source=crunchbase&utm_medium=export&utm_campaign=odm_csv",
    "domain": "acquia.com",
    "homepage_url": "http://acquia.com",
    "logo_url": "https://res.cloudinary.com/crunchbase-production/image/upload/rbjvr1i7q5w5f430iavw",
    "facebook_url": "http://www.facebook.com/acquia",
    "twitter_url": "http://twitter.com/Acquia",
    "linkedin_url": "http://www.linkedin.com/company/167056",
    "combined_stock_symbols": null,
    "city": "Boston",
    "region": "Massachusetts",
    "country_code": "USA",
    "short_description": "Acquia specializes in providing cloud-based digital experience management solutions."
  },
  {
    "uuid": "135f427d-7f25-9492-1ffe-801b35b6b988",
    "name": "Academic Capital Exchange",
    "type": "organization",
    "primary_role": "company",
    "cb_url": "https://www.crunchbase.com/organization/academic-capital-exchange?utm_source=crunchbase&utm_medium=export&utm_campaign=odm_csv",
    "domain": "academicapital.com",
    "homepage_url": "http://www.academicapital.com",
    "logo_url": "https://res.cloudinary.com/crunchbase-production/image/upload/v1397183889/5fe5afd0210d774cbb5b5061010fb9a0.jpg",
    "facebook_url": null,
    "twitter_url": null,
    "linkedin_url": null,
    "combined_stock_symbols": null,
    "city": "Chicago",
    "region": "Illinois",
    "country_code": "USA",
    "short_description": "Academic Capital Exchange (ACE), a peer-to-peer student loan marketplace, helps students obtain financial support and professional guidance."
  }
]

The record count of this newly-saved file hasn't changed, it's still 31 rows long

## Question 4: Read the JSON objects from the created file back into a data frame, filter for companies based in New York (city):
- Print the records in the resulting data frame
- Write the output to a webpage using Flask

In [27]:
# pip install flask
from flask import Flask, request # Need request for Question 6, but using same server for both

# Put it on a webpage
app = Flask(__name__) # Telling flask this is the main file
@app.route("/nyc")    # Giving flask a decorator to tell flask when someone visits the URL, run the below function

def index():
    with open("US_Based_Ac_Companies.json", "r") as f:
        usaac_df = pd.DataFrame(json.load(f)) # Reads it back as a dataframe

    nyc = usaac_df[usaac_df["city"] == "New York"] # Filters for NYC-based companies, there is only one
    
    return nyc.to_html() # Converts dataframe to HTML table, sends to browser

# if condition ensures the server only runs when I execute this file directly, dunder variables
# Going to comment out the app.run() instance below so I can run it at bottom and use this server for Qs 5 & 6

# if __name__ == "__main__": 
    # app.run(host='localhost', port=1997) 
    
    # http://localhost:1997/nyc
    # when I run this, and visit the URL, flask looks up the function registered to the route and calls it automatically

## Question 5: Implement Flask API functions to Return a list of Crunchbase companies based in a user submitted City from the original dataset (4 Points)
- Take a user input through a form to return a list of JSON objects from the city queried

I could just create a text box for the user's input, but they're doubtfully going to enter a city value that actually matches the format of the cities that are values in the dataset. So let's just give them a drop-down reference of which city they want to look at companies from.

In [28]:
# Going to use same server/port as previous cell and then I can visit both URls after I run this cell. 
@app.route('/cityofchoice', methods=['GET', 'POST']) # This route accepts GET for visiting page, POST for submitting form
def form():
    cities = sorted(nonnull["city"].dropna().unique().tolist()) # Alphabetize list of unique non-null city values
    if request.method == 'GET': # Checks how page is accessed
        options = "".join([f'<option value="{city}">{city}</option>' for city in cities])
        # use f-string with a list comprehension dynamically builds an HTML option tag for every city in the list
        # the value= gets sent to Flask on submission, the text between tags shows to the form submitter
        # "".join() joins all the tags in one big spaceless HTML block
        return f'''
            <form method="POST">
                <label for="city">Select a city:</label>
                <select name="city" id="city">
                    {options}
                </select>
                <button type="submit">Submit</button>
            </form>
        ''' # on the 'select' line, name="city" is the key we use to get values, 
            # Select renders dropdown menu instead of a free-form text box 
    else:
        try:
            city = request.form['city']
            city_df = nonnull[nonnull["city"] == city] # Filters OG dataframe for whatever the user input
            city_json = json.loads(city_df.to_json(orient="records")) # Converts the df output to JSON objects, one per company
            return json.dumps(city_json, indent=2) # Sends formatted JSON back to browser as a response
        except KeyError: # If the city key is for some reason missing from form data, print the below message
            return "Please enter a city in the form."

if __name__ == "__main__":
    app.run(host='localhost', port=1997) # Using this server for both Question 5 and 6
    # So then I visited http://localhost:1997/nyc AND http://localhost:1997/cityofchoice
    # Man there are a lot of cities to choose from...

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://localhost:1997/ (Press CTRL+C to quit)

## Question 6: Git Version Control

- Initialize a Git repository for your project directory.
- Commit your code (data.py, Flask application script) with a descriptive message (e.g., "Initial commit: Flask API with data and route").
- Push your code to a remote Git repository (e.g., GitHub). Submit the repository URL in the answer cell.

In [ ]:
#Write git repo link

# Assignment End